# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BookShelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SendbirdProject
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxSwiftExt'
  pod 'RealmSwift'
  pod 'SDWebImage'
  pod 'SnapKit'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'Then'
  pod 'Reusable'
  pod 'ActiveLabel'
  pod 'Cosmos'

  target 'BookShelfTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
  	pod 'Nimble'
  end

end
